addons:
  postgresql: 9.6

before_script:
  - psql -c 'create database url_shortener_app_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
