development:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_app_development
  username: postgres
  password: postgres
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: infiniteach_dev
  username: postgres
  password: postgres
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_app_test
  username: postgres
  password: postgres
  host: localhost
